version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEB5GPT_MONTHLY_USAGE_LIMIT_USD: 30
